nodeLinker: pnp

plugins:
  - checksum: f976aecfcf6f3a10b5340aea2d054e21a672b108a50159498a345a6d85ba2fe12c728f10266e82ce8cf2d6c5e3d3fd3b302997c41ac34b4a4b03511a69391e01
    path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://github.com/mskelton/yarn-plugin-outdated/raw/v3.2.3/bundles/@yarnpkg/plugin-outdated.js"

yarnPath: .yarn/releases/yarn-4.0.0-rc.42.cjs
